<?php /** @var \JustShout\Gfs\Block\Html\Head $block */ ?>

<script>
    require([
        'moment'
    ], function(moment) {
        window.moment = moment;
        return moment;
    });
</script>

<style type="text/css">
    #widgetContainer .header {
        background: <?= $block->getColorPrimary() ?>;
    }

    #widgetContainer .header h3,
    #widgetContainer .header label {
        color: <?= $block->getColorSecondary() ?>;
    }

    #widgetContainer span.price {
        color: <?= $block->getColorTertiary() ?>;
    }
</style>
